# Generated by Django 5.2.8 on 2025-11-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
